### PR TITLE
Update simpleclient.html

### PR DESCRIPTION
**Pull request by sadfuzzy**
Remove absent file link

### CODE REVIEW

**Comment by sstrigler** [comment]
Hi, thanks for your contribution. I'm a bit undecided though. The idea is to show how to build a real world client. For this you'd create the "missing" file by doing a make.

../src/JSJaC.js is mostly meant for being used when you'd be developing on JSJaC itself to ease debugging.

**Comment by sadfuzzy** [comment]
It was breaking the app, as I remember

**Comment by sadfuzzy** [comment]
So I removed the link

**Comment by sstrigler** [comment]
Not sure how would a comment break the app?

**Comment by sadfuzzy** [comment]
Line 6 (  <script type="text/javascript" src="../jsjac.js"></script> )
not comment

**Comment by sstrigler** [comment]
Oh, yeah, sorry. 🙈

Now I understand. So the thing is, `../jsjac.js` is a compiled file. You need to run `make` in order to get it. But that's the preferred way how to actually use jsjac in real world applications. You don't want to include `../src/JSJaC.js` because it loads each single file one by one which results in a lot of unnecessary request and also `../jsjac.js` is compressed in contrast to including files from `../src`. `simpleclient.html` is meant to show you how to create a real world application in first place.

Maybe we should add a short note to the README then?

**Comment by sadfuzzy** [comment]
@sstrigler, got it :) thanks. It will help a lot)

**Pull request closed without merging**
